# Generated by Django 2.1.7 on 2019-03-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20190207_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_appointments', to='users.User2')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('line_index', models.PositiveIntegerField()),
                ('approx_time', models.DateTimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_to', to='appointments.Appointment')),
                ('registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_appointments', to='users.User2')),
            ],
        ),
    ]
